#------------------------------------
# Analysis options
#------------------------------------
results: "/Users/margotlavitt/Sum22/phide_piper_dev/results/"

#------------------------------------
# Resource options
#------------------------------------
resources: "/Users/margotlavitt/resources/"
# Default: MGV viruses
virus_db: "/Users/margotlavitt/resources/mgv_db/mgv_votu_reps.fasta"
virus_db_meta: "/Users/margotlavitt/resources/mgv_db/mgv_metadata.tsv"
# if sample is a bulk metagenome (or you want to make your own CRISPR spacer database) then spacer_db and spacer_db_meta 
# should be set to None, the MAGs to be used should be put in the bacteria_db and bacteria_db_meta fields, and the
# include_spacer_identification flag should be set to True
# Default: UHGG Spacers
spacer_db: "/labdata3/hoffdata/Shared/resources/crispr_spacers/uhgg_spacers.fna"
spacer_db_meta: "/labdata3/hoffdata/Shared/resources/crispr_spacers/uhgg_spacers_metadata.tsv"
# if sample is a bulk metagenome, one of the workflows shown below should be run and the MAGs should be used as the input
# starting at the virus identification module. Additionally, the MAGs should be input here as the bacteria db directory
# Default: UHGG MAGs
bacteria_db: "/labdata3/hoffdata/Shared/resources/bacteria_db/bacteria/bacteria_db_download_complete"
bacteria_db_meta: "/labdata3/hoffdata/Shared/resources/bacteria_db/uhog_genome-all_metadata.tsv"
# Default: VPF
function_db: ""
function_db_meta: ""

#------------------------------------
# Rule customization 
#------------------------------------ 
### Preprocessing ###
read_preprocessing:
  clumpify_args: "dedupe=t optical=t spany=t adjacent=t"
  kneaddata_args: "--remove-intermediate-output --verbose --trimmomatic $CONDA_PREFIX/share/trimmomatic-0.39-2"
  kneaddata_threads: 10

### Virus pipeline modules ###
virus_enrichment:
  viromeqc_arguments: ""
  viromeqc_threads: 10
  min_enrichment: 0

read_assembly:
  metaspades_arguments: ""
  metaspades_threads: 10
  assembly_output: "contigs"
  quast_arguments: "--max-ref-num 0"
  min_contig_length: 1000

virus_identification:
  assembled_contigs: ""
  run_mgv: True
  mgv_threads: 10
  run_virsorter: True
  virsorter_cat: [1,2,3,4,5,6]
  virsorter_arguments: "--db 2 --diamond"
  virsorter_threads: 10
  run_virfinder: True
  virfinder_min_score: 0.9
  virfinder_threads: 10
  run_virsorter2: True
  virsorter2_min_score: 0.9
  virsorter2_arguments: "--keep-original-seq --include-groups dsDNAphage"
  virsorter2_threads: 10
  run_vibrant: True
  vibrant_arguments: "-no_plot"
  vibrant_threads: 10
  run_deepvirfinder: True
  deepvirfinder_min_score: 0.9
  deepvirfinder_threads: 10
  run_kraken2: True
  kraken2_arguments: ""
  kraken2_threads: 10

virus_clustering:
  viral_contigs: ""
  derep_min_ani: 0.99
  derep_min_tcov: 0.99
  derep_min_qcov: 0
  cluster_with_virusdb: True
  min_virusdb_breadth: 25
  min_virusdb_length: 0
  min_ani: 95
  min_tcov: 85
  min_qcov: 0
  blast_threads: 10

virus_quality:
  clustered_viral_contigs: ""
  checkv_arguments: ""
  checkv_threads: 10
  min_completeness: 50
  max_bacterial_genes: 1
  min_viral_genes: 0

spacer_identification:
  run_pilercr: True
  pilercr_threads: 10
  run_crt: True
  crt_threads: 10
  run_crisprdetect: True
  crisprdetect_threads: 10
  run_crisprcasfinder: True
  crisprcasfinder_threads: 10
  run_crispridentify: True
  crispridentify_threads: 10

virus_host:
  quality_filtered_contigs: ""
  run_spacer_blast: True
  blast_threads: 10
  max_spacer_mismatch: 1
  min_spacer_coverage: 95
  min_spacer_agreement: 70
  run_phist: True
  min_phist_common_kmers: 10
  min_phist_agreement: 70
  phist_threads: 10
  run_rafah: True
  rafah_threads: 10
  # rafah:
  # hostg:


virus_taxonomy:
  quality_filtered_contigs: ""
  run_diamond_taxonomy: True
  diamond_threads: 10
  min_protein_agreement: 70
  min_protein_hits: 1
  min_protein_hits_genus: 3
  min_aai_genus: 40
  min_protein_hits_family: 2
  min_aai_family: 30
  run_vpfclass: True
  # vpf_class:
  run_hmmer: True
  # hmmer:
  run_vcontact2: True
  vcontact2_threads: 10

virus_lifestyle:
  quality_filtered_contigs: ""
  run_bacphlip: True
  bacphlip_confidence: 0.5
  include_checkv_proviruses: True

virus_function:
  quality_filtered_contigs: ""
  run_hmmer: True
  hmmer_threads: 10
  # hmmer
  run_dramv: True
  dramv_threads: 10
  # dramv: 
  include_vibrant_annotations: True

virus_abundance:
  quality_filtered_contigs: ""
  run_metapop: True
  min_breadth: 50
  min_depth: 1
  min_length: 0
  metapop_threads: 10
  run_kraken: True
  kraken_threads: 10
  taxon_level: "F"

read_abundance:
  bowtie_build_extra_args: ""
  bowtie_align_extra_args: ""
  kraken_db: "/Users/margotlavitt/Sum22/phide_piper_dev/results/READ_ABUNDANCE/02_kraken2_bracken/mgv_kraken2db/"
  kraken2_extra_args: ""
  kraken_align_extra_args: ""
  bracken_build_extra_args: ""
  bracken_extra_args: ""
  virus_dir: "/Users/margotlavitt/Sum22/phide_piper_dev/resources/mgv_db/"
  metapop_extra_args: ""
  inStrain_profile_extra_args: ""
  inStrain_compare_extra_args: ""


spacer_prediction:
  in_dir: "/Users/margotlavitt/resources/bacteria_db/bacteria/"
  CRISPRidentify_extra_args: ""
